exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - ".editorconfig"
  - "vendor"
  - "docker-compose.yml"
  - "Dockerfile"

defaults:
  - values:
      layout: "default_ja"
  - scope:
      path: ""
      type: candidates_ja
    values:
      layout: candidates_ja
  - scope:
      path: ""
      type: candidates_en
    values:
      layout: candidates_en
  - scope:
      path: ""
      type: jobs
    values:
      layout: job

collections:
  candidates_ja:
    output: true
    permalink: /ja/candidates/:path/
  candidates_en:
    output: true
    permalink: /en/candidates/:path/
  jobs:
    output: true
    permalink: /jobs/:path/

safe: true
lsi: false

# Custom variables
url: "http://2017.scalamatsuri.org"
ja:
  twitter: scala_jp
en:
  twitter: scalamatsuri
plans:
  - shogun
  - daimyo
  - hatamoto
  - samurai
  - ninja
