exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - ".gitignore"
  - ".editorconfig"
  - "vendor"

defaults:
  - values:
      layout: "default_ja"
  - scope:
      path: ""
      type: candidates_ja
    values:
      layout: candidates_ja
  - scope:
      path: ""
      type: candidates_en
    values:
      layout: candidates_en

collections:
  candidates_ja:
    output: true
    permalink: /ja/candidates/:path/
  candidates_en:
    output: true
    permalink: /en/candidates/:path/

safe: true
lsi: false

# Custom variables
url: "http://2017.scalamatsuri.org"
ja:
  twitter: scala_jp
en:
  twitter: scalamatsuri
